//HintName: EnumToClassAttribute.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.EnumToClass;

/// <summary>
/// Generates const string values for each enum field.
/// Makes class/record decorated with the attribute a closed type.
/// </summary>
/// <typeparam name="T">Enum type parameter</typeparam>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
[global::System.Diagnostics.Conditional("ENUM_TO_CLASS_GENERATOR_ATTRIBUTES")]
internal sealed class EnumToClassAttribute<T> : global::System.Attribute
    where T : global::System.Enum
{
    public bool WithDescription { get; set; }
}

/// <summary>
/// Projects <typeparamref name="TAttribute"/> from each enum member onto a property
/// of the EnumToClass host. Use multiple times for multiple attribute types.
/// </summary>
/// <typeparam name="TAttribute">Attribute type applied to enum members.</typeparam>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
[global::System.Diagnostics.Conditional("ENUM_TO_CLASS_GENERATOR_ATTRIBUTES")]
internal sealed class EnumToClassPropertyAttribute<TAttribute> : global::System.Attribute
    where TAttribute : global::System.Attribute
{
    /// <summary>
    /// Generated property name. Default: type name of TAttribute without "Attribute" suffix.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// When true, collects all applications of TAttribute on a member as an array.
    /// When false (default), uses the first application (or null / default).
    /// </summary>
    public bool AsArray { get; set; }

    /// <summary>
    /// When set, project this member of TAttribute (property or constructor parameter)
    /// instead of the attribute instance. Single segment only (e.g. "Name").
    /// </summary>
    public string? Source { get; set; }

    /// <summary>
    /// When true, emit a bool host property that is true when TAttribute is applied
    /// on the enum member. Incompatible with AsArray and Source.
    /// </summary>
    public bool AsBoolean { get; set; }
}