//HintName: Host_Constructors.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.Tests
{
    public partial class Host : global::System.IEquatable<Host>
    {
        private Host(VRT.Generators.Tests.E value)
        {
            Name = value.ToString();
            IsEmpty = value == default(VRT.Generators.Tests.E);
            Value = value;
            
        }
        public string Name { get; }
        public VRT.Generators.Tests.E Value { get; }
        public bool IsEmpty { get; }

        
        public global::VRT.Generators.Tests.MetaAttribute? Meta { get; private init; }
        public bool Equals(Host? other)
    => other is not null && other.Value == Value;

public override bool Equals(object? obj)
    => obj is Host other && Equals(other);

public override int GetHashCode() => Value.GetHashCode();

public static bool operator ==(Host? left, Host? right)
    => left is null ? right is null : left.Equals(right);

public static bool operator !=(Host? left, Host? right)
    => !(left == right);

        public override string ToString() => Name;

        public static global::System.Collections.Generic.IReadOnlyCollection<Host> GetAll() => ValueByNameMap.Values;

        public static global::System.Collections.Generic.IEnumerable<Host> GetByName(global::System.Collections.Generic.IEnumerable<string> names)
            => global::System.Linq.Enumerable.Where(global::System.Linq.Enumerable.Select(names, GetByName), static p => p.IsEmpty == false);

        public static Host GetByName(string name)
        {
            return ValueByNameMap.TryGetValue(name, out var value)
                ? value
                : Empty;
        }

        public static bool TryGetByName(string name, out Host value)
        {
            if (ValueByNameMap.TryGetValue(name, out value!))
            {
                return true;
            }

            value = Empty;
            return false;
        }

        public static implicit operator Host(string name) => GetByName(name);
        public static implicit operator string(Host value) => value.Name;
        public static implicit operator VRT.Generators.Tests.E(Host value) => value.Value;
        public static implicit operator Host(VRT.Generators.Tests.E value) => GetByName(value.ToString());
        public static implicit operator int(Host value) => (int) value.Value;
        public static implicit operator Host(int value) => (VRT.Generators.Tests.E)value;
    }
}