//HintName: Host_Constants.g.cs
// <auto-generated />
#nullable enable

namespace VRT.Generators.Tests
{
    public partial class Host : global::System.IEquatable<Host>
    {
        private static readonly global::System.Collections.ObjectModel.ReadOnlyDictionary<string, Host> ValueByNameMap = new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, Host>(new global::System.Collections.Generic.Dictionary<string, Host>()
        {
            ["A"] = new Host(VRT.Generators.Tests.E.A) { Meta = new global::VRT.Generators.Tests.MetaAttribute() }
        });

        public static Host Empty { get; } = ValueByNameMap["A"];

        /// <summary>
        /// A
        /// </summary>
        public const string A = "A";

        /// <summary>
        /// A
        /// </summary>
        public static Host AInstance { get; } = ValueByNameMap["A"];
    }
}