//HintName: RoleTypeClass_Constructors.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.Tests
{
    public partial class RoleTypeClass : global::System.IEquatable<RoleTypeClass>
    {
        private RoleTypeClass(VRT.Generators.Tests.RoleTypes value)
        {
            Name = value.ToString();
            IsEmpty = value == default(VRT.Generators.Tests.RoleTypes);
            Value = value;
            
        }
        public string Name { get; }
        public VRT.Generators.Tests.RoleTypes Value { get; }
        public bool IsEmpty { get; }

        
        public global::VRT.Generators.Tests.PermissionAttribute[] Permissions { get; private init; } = global::System.Array.Empty<global::VRT.Generators.Tests.PermissionAttribute>();
        public bool Equals(RoleTypeClass? other)
    => other is not null && other.Value == Value;

public override bool Equals(object? obj)
    => obj is RoleTypeClass other && Equals(other);

public override int GetHashCode() => Value.GetHashCode();

public static bool operator ==(RoleTypeClass? left, RoleTypeClass? right)
    => left is null ? right is null : left.Equals(right);

public static bool operator !=(RoleTypeClass? left, RoleTypeClass? right)
    => !(left == right);

        public override string ToString() => Name;

        public static global::System.Collections.Generic.IReadOnlyCollection<RoleTypeClass> GetAll() => ValueByNameMap.Values;

        public static global::System.Collections.Generic.IEnumerable<RoleTypeClass> GetByName(global::System.Collections.Generic.IEnumerable<string> names)
            => global::System.Linq.Enumerable.Where(global::System.Linq.Enumerable.Select(names, GetByName), static p => p.IsEmpty == false);

        public static RoleTypeClass GetByName(string name)
        {
            return ValueByNameMap.TryGetValue(name, out var value)
                ? value
                : Empty;
        }

        public static bool TryGetByName(string name, out RoleTypeClass value)
        {
            if (ValueByNameMap.TryGetValue(name, out value!))
            {
                return true;
            }

            value = Empty;
            return false;
        }

        public static implicit operator RoleTypeClass(string name) => GetByName(name);
        public static implicit operator string(RoleTypeClass value) => value.Name;
        public static implicit operator VRT.Generators.Tests.RoleTypes(RoleTypeClass value) => value.Value;
        public static implicit operator RoleTypeClass(VRT.Generators.Tests.RoleTypes value) => GetByName(value.ToString());
        public static implicit operator int(RoleTypeClass value) => (int) value.Value;
        public static implicit operator RoleTypeClass(int value) => (VRT.Generators.Tests.RoleTypes)value;
    }
}