//HintName: RoleTypeClass_Constants.g.cs
// <auto-generated />
#nullable enable

namespace VRT.Generators.Tests
{
    public partial class RoleTypeClass : global::System.IEquatable<RoleTypeClass>
    {
        private static readonly global::System.Collections.ObjectModel.ReadOnlyDictionary<string, RoleTypeClass> ValueByNameMap = new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, RoleTypeClass>(new global::System.Collections.Generic.Dictionary<string, RoleTypeClass>()
        {
            ["Editor"] = new RoleTypeClass(VRT.Generators.Tests.RoleTypes.Editor) { Permissions = new global::VRT.Generators.Tests.PermissionAttribute[] { new global::VRT.Generators.Tests.PermissionAttribute("read"), new global::VRT.Generators.Tests.PermissionAttribute("write") } },
            ["Viewer"] = new RoleTypeClass(VRT.Generators.Tests.RoleTypes.Viewer) { Permissions = new global::VRT.Generators.Tests.PermissionAttribute[] { new global::VRT.Generators.Tests.PermissionAttribute("read") } },
            ["Guest"] = new RoleTypeClass(VRT.Generators.Tests.RoleTypes.Guest) { Permissions = global::System.Array.Empty<global::VRT.Generators.Tests.PermissionAttribute>() }
        });

        public static RoleTypeClass Empty { get; } = ValueByNameMap["Editor"];

        /// <summary>
        /// Editor
        /// </summary>
        public const string Editor = "Editor";
        /// <summary>
        /// Viewer
        /// </summary>
        public const string Viewer = "Viewer";
        /// <summary>
        /// Guest
        /// </summary>
        public const string Guest = "Guest";

        /// <summary>
        /// Editor
        /// </summary>
        public static RoleTypeClass EditorInstance { get; } = ValueByNameMap["Editor"];
        /// <summary>
        /// Viewer
        /// </summary>
        public static RoleTypeClass ViewerInstance { get; } = ValueByNameMap["Viewer"];
        /// <summary>
        /// Guest
        /// </summary>
        public static RoleTypeClass GuestInstance { get; } = ValueByNameMap["Guest"];
    }
}