#pragma warning disable IDE0130 // Namespace does not match folder structure
namespace VRT.Generators;
#pragma warning restore IDE0130 // Namespace does not match folder structure

internal static class EnumToClassAttributeDefinition
{
    public const string NamespaceName = "VRT.Generators.EnumToClass";
    public const string AttributeTypeName = "EnumToClassAttribute";
    public const string WithDescriptionPropertyName = "WithDescription";
    public const string FullyQualifiedName = $"{NamespaceName}.{AttributeTypeName}`1";

    public const string PropertyAttributeTypeName = "EnumToClassPropertyAttribute";
    public const string PropertyAttributeNamePropertyName = "Name";
    public const string PropertyAttributeFullyQualifiedMetadataName = $"{NamespaceName}.{PropertyAttributeTypeName}`1";

    public const string SourceCode =
        $$"""
        // <auto-generated />
        #nullable enable
        namespace {{NamespaceName}};

        /// <summary>
        /// Generates const string values for each enum field.
        /// Makes class/record decorated with the attribute a closed type.
        /// </summary>
        /// <typeparam name="T">Enum type parameter</typeparam>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
        [global::System.Diagnostics.Conditional("ENUM_TO_CLASS_GENERATOR_ATTRIBUTES")]
        internal sealed class {{AttributeTypeName}}<T> : global::System.Attribute
            where T : global::System.Enum
        {
            public bool WithDescription { get; set; }
        }

        /// <summary>
        /// Projects <typeparamref name="TAttribute"/> from each enum member onto a nullable
        /// property of the EnumToClass host. Use multiple times for multiple attribute types.
        /// </summary>
        /// <typeparam name="TAttribute">Attribute type applied to enum members.</typeparam>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
        [global::System.Diagnostics.Conditional("ENUM_TO_CLASS_GENERATOR_ATTRIBUTES")]
        internal sealed class {{PropertyAttributeTypeName}}<TAttribute> : global::System.Attribute
            where TAttribute : global::System.Attribute
        {
            /// <summary>
            /// Generated property name. Default: type name of TAttribute without "Attribute" suffix.
            /// </summary>
            public string? Name { get; set; }
        }
        """;
}
