//HintName: SpecialElementClass_Constructors.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.Tests
{
    public partial class SpecialElementClass : global::System.IEquatable<SpecialElementClass>
    {
        private SpecialElementClass(VRT.Generators.Tests.SpecialElements value, string description)
        {
            Name = value.ToString();
            IsEmpty = value == default(VRT.Generators.Tests.SpecialElements);
            Value = value;
            Description = description;
        }
        public string Name { get; }
        public VRT.Generators.Tests.SpecialElements Value { get; }
        public bool IsEmpty { get; }

        public string Description { get; }
        public bool Equals(SpecialElementClass? other)
    => other is not null && other.Value == Value;

public override bool Equals(object? obj)
    => obj is SpecialElementClass other && Equals(other);

public override int GetHashCode() => Value.GetHashCode();

public static bool operator ==(SpecialElementClass? left, SpecialElementClass? right)
    => left is null ? right is null : left.Equals(right);

public static bool operator !=(SpecialElementClass? left, SpecialElementClass? right)
    => !(left == right);

        public override string ToString() => Name;

        public static global::System.Collections.Generic.IReadOnlyCollection<SpecialElementClass> GetAll() => ValueByNameMap.Values;

        public static global::System.Collections.Generic.IEnumerable<SpecialElementClass> GetByName(global::System.Collections.Generic.IEnumerable<string> names)
            => global::System.Linq.Enumerable.Where(global::System.Linq.Enumerable.Select(names, GetByName), static p => p.IsEmpty == false);

        public static SpecialElementClass GetByName(string name)
        {
            return ValueByNameMap.TryGetValue(name, out var value)
                ? value
                : Empty;
        }

        public static bool TryGetByName(string name, out SpecialElementClass value)
        {
            if (ValueByNameMap.TryGetValue(name, out value!))
            {
                return true;
            }

            value = Empty;
            return false;
        }

        public static implicit operator SpecialElementClass(string name) => GetByName(name);
        public static implicit operator string(SpecialElementClass value) => value.Name;
        public static implicit operator VRT.Generators.Tests.SpecialElements(SpecialElementClass value) => value.Value;
        public static implicit operator SpecialElementClass(VRT.Generators.Tests.SpecialElements value) => GetByName(value.ToString());
        public static implicit operator int(SpecialElementClass value) => (int) value.Value;
        public static implicit operator SpecialElementClass(int value) => (VRT.Generators.Tests.SpecialElements)value;
    }
}