//HintName: SpecialElementClass_Constants.g.cs
// <auto-generated />
#nullable enable

namespace VRT.Generators.Tests
{
    public partial class SpecialElementClass : global::System.IEquatable<SpecialElementClass>
    {
        private static readonly global::System.Collections.ObjectModel.ReadOnlyDictionary<string, SpecialElementClass> ValueByNameMap = new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, SpecialElementClass>(new global::System.Collections.Generic.Dictionary<string, SpecialElementClass>()
        {
            ["Quoted"] = new SpecialElementClass(VRT.Generators.Tests.SpecialElements.Quoted, "He said \"hi\"\nand left"),
            ["Plain"] = new SpecialElementClass(VRT.Generators.Tests.SpecialElements.Plain, "plain")
        });

        public static SpecialElementClass Empty { get; } = ValueByNameMap["Quoted"];

        /// <summary>
/// He said "hi"
                /// and left
/// </summary>
        public const string Quoted = "Quoted";
        /// <summary>
/// plain
/// </summary>
        public const string Plain = "Plain";

        /// <summary>
/// He said "hi"
                /// and left
/// </summary>
        public static SpecialElementClass QuotedInstance { get; } = ValueByNameMap["Quoted"];
        /// <summary>
/// plain
/// </summary>
        public static SpecialElementClass PlainInstance { get; } = ValueByNameMap["Plain"];
    }
}