//HintName: MetadataElementClass_Constants.g.cs
// <auto-generated />
#nullable enable

namespace VRT.Generators.Tests
{
    public partial class MetadataElementClass : global::System.IEquatable<MetadataElementClass>
    {
        private static readonly global::System.Collections.ObjectModel.ReadOnlyDictionary<string, MetadataElementClass> ValueByNameMap = new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, MetadataElementClass>(new global::System.Collections.Generic.Dictionary<string, MetadataElementClass>()
        {
            ["Both"] = new MetadataElementClass(VRT.Generators.Tests.MetadataElements.Both) { Metadata1 = new global::VRT.Generators.Tests.Metadata1Attribute("alpha"), Meta2 = new global::VRT.Generators.Tests.Metadata2Attribute() },
            ["OnlySecond"] = new MetadataElementClass(VRT.Generators.Tests.MetadataElements.OnlySecond) { Metadata1 = null, Meta2 = new global::VRT.Generators.Tests.Metadata2Attribute() },
            ["Bare"] = new MetadataElementClass(VRT.Generators.Tests.MetadataElements.Bare) { Metadata1 = null, Meta2 = null }
        });

        public static MetadataElementClass Empty { get; } = ValueByNameMap["Both"];

        /// <summary>
        /// Both
        /// </summary>
        public const string Both = "Both";
        /// <summary>
        /// OnlySecond
        /// </summary>
        public const string OnlySecond = "OnlySecond";
        /// <summary>
        /// Bare
        /// </summary>
        public const string Bare = "Bare";

        /// <summary>
        /// Both
        /// </summary>
        public static MetadataElementClass BothInstance { get; } = ValueByNameMap["Both"];
        /// <summary>
        /// OnlySecond
        /// </summary>
        public static MetadataElementClass OnlySecondInstance { get; } = ValueByNameMap["OnlySecond"];
        /// <summary>
        /// Bare
        /// </summary>
        public static MetadataElementClass BareInstance { get; } = ValueByNameMap["Bare"];
    }
}