//HintName: MetadataElementClass_Constructors.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.Tests
{
    public partial class MetadataElementClass : global::System.IEquatable<MetadataElementClass>
    {
        private MetadataElementClass(VRT.Generators.Tests.MetadataElements value)
        {
            Name = value.ToString();
            IsEmpty = value == default(VRT.Generators.Tests.MetadataElements);
            Value = value;
            
        }
        public string Name { get; }
        public VRT.Generators.Tests.MetadataElements Value { get; }
        public bool IsEmpty { get; }

        
        public global::VRT.Generators.Tests.Metadata1Attribute? Metadata1 { get; private init; }
                    public global::VRT.Generators.Tests.Metadata2Attribute? Meta2 { get; private init; }
        public bool Equals(MetadataElementClass? other)
    => other is not null && other.Value == Value;

public override bool Equals(object? obj)
    => obj is MetadataElementClass other && Equals(other);

public override int GetHashCode() => Value.GetHashCode();

public static bool operator ==(MetadataElementClass? left, MetadataElementClass? right)
    => left is null ? right is null : left.Equals(right);

public static bool operator !=(MetadataElementClass? left, MetadataElementClass? right)
    => !(left == right);

        public override string ToString() => Name;

        public static global::System.Collections.Generic.IReadOnlyCollection<MetadataElementClass> GetAll() => ValueByNameMap.Values;

        public static global::System.Collections.Generic.IEnumerable<MetadataElementClass> GetByName(global::System.Collections.Generic.IEnumerable<string> names)
            => global::System.Linq.Enumerable.Where(global::System.Linq.Enumerable.Select(names, GetByName), static p => p.IsEmpty == false);

        public static MetadataElementClass GetByName(string name)
        {
            return ValueByNameMap.TryGetValue(name, out var value)
                ? value
                : Empty;
        }

        public static bool TryGetByName(string name, out MetadataElementClass value)
        {
            if (ValueByNameMap.TryGetValue(name, out value!))
            {
                return true;
            }

            value = Empty;
            return false;
        }

        public static implicit operator MetadataElementClass(string name) => GetByName(name);
        public static implicit operator string(MetadataElementClass value) => value.Name;
        public static implicit operator VRT.Generators.Tests.MetadataElements(MetadataElementClass value) => value.Value;
        public static implicit operator MetadataElementClass(VRT.Generators.Tests.MetadataElements value) => GetByName(value.ToString());
        public static implicit operator int(MetadataElementClass value) => (int) value.Value;
        public static implicit operator MetadataElementClass(int value) => (VRT.Generators.Tests.MetadataElements)value;
    }
}