//HintName: TestElementRecord_Constructors.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.Tests
{
    public partial record TestElementRecord
    {
        private TestElementRecord(VRT.Generators.Tests.TestElements value, string description)
        {
            Name = value.ToString();
            IsEmpty = value == default(VRT.Generators.Tests.TestElements);
            Value = value;
            Description = description;
        }
        public string Name { get; }
        public VRT.Generators.Tests.TestElements Value { get; }
        public bool IsEmpty { get; }

        public string Description { get; }
        

        public override string ToString() => Name;

        public static global::System.Collections.Generic.IReadOnlyCollection<TestElementRecord> GetAll() => ValueByNameMap.Values;

        public static global::System.Collections.Generic.IEnumerable<TestElementRecord> GetByName(global::System.Collections.Generic.IEnumerable<string> names)
            => global::System.Linq.Enumerable.Where(global::System.Linq.Enumerable.Select(names, GetByName), static p => p.IsEmpty == false);

        public static TestElementRecord GetByName(string name)
        {
            return ValueByNameMap.TryGetValue(name, out var value)
                ? value
                : Empty;
        }

        public static bool TryGetByName(string name, out TestElementRecord value)
        {
            if (ValueByNameMap.TryGetValue(name, out value!))
            {
                return true;
            }

            value = Empty;
            return false;
        }

        public static implicit operator TestElementRecord(string name) => GetByName(name);
        public static implicit operator string(TestElementRecord value) => value.Name;
        public static implicit operator VRT.Generators.Tests.TestElements(TestElementRecord value) => value.Value;
        public static implicit operator TestElementRecord(VRT.Generators.Tests.TestElements value) => GetByName(value.ToString());
        public static implicit operator int(TestElementRecord value) => (int) value.Value;
        public static implicit operator TestElementRecord(int value) => (VRT.Generators.Tests.TestElements)value;
    }
}