//HintName: TestElementRecord_Constants.g.cs
//<auto-generated />     
using System.Collections.Generic;
using System.Collections.ObjectModel;
#nullable enable

namespace VRT.Generators.Tests
{
    public partial record TestElementRecord            
    {
        private static readonly ReadOnlyDictionary<string, TestElementRecord> ValueByNameMap = new ReadOnlyDictionary<string, TestElementRecord>(new Dictionary<string, TestElementRecord>()
        {
            ["None"] = new TestElementRecord(VRT.Generators.Tests.TestElements.None,"Empty element"),
            ["Element1"] = new TestElementRecord(VRT.Generators.Tests.TestElements.Element1,"First element of enum"),
            ["Element2"] = new TestElementRecord(VRT.Generators.Tests.TestElements.Element2,"Second element of enum"),
            ["Element3"] = new TestElementRecord(VRT.Generators.Tests.TestElements.Element3,"This is element 3 of the test enum"),
            ["Element4"] = new TestElementRecord(VRT.Generators.Tests.TestElements.Element4,"This test element calculates the factorial of a given non-negative integer."),
            ["Element5"] = new TestElementRecord(VRT.Generators.Tests.TestElements.Element5,"The fifth element")
        });
        /// <summary>
    /// Empty element
    /// </summary>

        public const string None = "None";
        /// <summary>
    /// First element of enum
    /// </summary>

        public const string Element1 = "Element1";
        /// <summary>
    /// Second element of enum
    /// </summary>

        public const string Element2 = "Element2";
        /// <summary>
/// This is element 3 of the test enum
/// </summary>
        public const string Element3 = "Element3";
        /// <summary>
    /// This test element calculates the factorial of a given non-negative integer.
    /// </summary>
    /// <remarks>
    /// The factorial of a number \( n \) is the product of all positive integers less than or equal to \( n \).
    /// For example, <c>factorial(5)</c> returns <c>120</c>.
    /// </remarks>

        public const string Element4 = "Element4";
        /// <summary>
    /// This is a fifth element.
    /// Multiline comment
    /// </summary>
    /// <remarks>
    /// A fifth element
    /// For example, <c>xxx(5)</c> returns <c>120</c>.
    /// </remarks>    

        public const string Element5 = "Element5";
    }
}