//HintName: NonZeroFirstClass_Constructors.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.Tests
{
    public partial class NonZeroFirstClass : global::System.IEquatable<NonZeroFirstClass>
    {
        private NonZeroFirstClass(VRT.Generators.Tests.NonZeroFirst value)
        {
            Name = value.ToString();
            IsEmpty = value == default(VRT.Generators.Tests.NonZeroFirst);
            Value = value;
            
        }
        public string Name { get; }
        public VRT.Generators.Tests.NonZeroFirst Value { get; }
        public bool IsEmpty { get; }

        
        
        public bool Equals(NonZeroFirstClass? other)
    => other is not null && other.Value == Value;

public override bool Equals(object? obj)
    => obj is NonZeroFirstClass other && Equals(other);

public override int GetHashCode() => Value.GetHashCode();

public static bool operator ==(NonZeroFirstClass? left, NonZeroFirstClass? right)
    => left is null ? right is null : left.Equals(right);

public static bool operator !=(NonZeroFirstClass? left, NonZeroFirstClass? right)
    => !(left == right);

        public override string ToString() => Name;

        public static global::System.Collections.Generic.IReadOnlyCollection<NonZeroFirstClass> GetAll() => ValueByNameMap.Values;

        public static global::System.Collections.Generic.IEnumerable<NonZeroFirstClass> GetByName(global::System.Collections.Generic.IEnumerable<string> names)
            => global::System.Linq.Enumerable.Where(global::System.Linq.Enumerable.Select(names, GetByName), static p => p.IsEmpty == false);

        public static NonZeroFirstClass GetByName(string name)
        {
            return ValueByNameMap.TryGetValue(name, out var value)
                ? value
                : Empty;
        }

        public static bool TryGetByName(string name, out NonZeroFirstClass value)
        {
            if (ValueByNameMap.TryGetValue(name, out value!))
            {
                return true;
            }

            value = Empty;
            return false;
        }

        public static implicit operator NonZeroFirstClass(string name) => GetByName(name);
        public static implicit operator string(NonZeroFirstClass value) => value.Name;
        public static implicit operator VRT.Generators.Tests.NonZeroFirst(NonZeroFirstClass value) => value.Value;
        public static implicit operator NonZeroFirstClass(VRT.Generators.Tests.NonZeroFirst value) => GetByName(value.ToString());
        public static implicit operator int(NonZeroFirstClass value) => (int) value.Value;
        public static implicit operator NonZeroFirstClass(int value) => (VRT.Generators.Tests.NonZeroFirst)value;
    }
}