//HintName: NonZeroFirstClass_Constants.g.cs
// <auto-generated />
#nullable enable

namespace VRT.Generators.Tests
{
    public partial class NonZeroFirstClass : global::System.IEquatable<NonZeroFirstClass>
    {
        private static readonly global::System.Collections.ObjectModel.ReadOnlyDictionary<string, NonZeroFirstClass> ValueByNameMap = new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, NonZeroFirstClass>(new global::System.Collections.Generic.Dictionary<string, NonZeroFirstClass>()
        {
            ["Alpha"] = new NonZeroFirstClass(VRT.Generators.Tests.NonZeroFirst.Alpha),
            ["Beta"] = new NonZeroFirstClass(VRT.Generators.Tests.NonZeroFirst.Beta),
            ["Zero"] = new NonZeroFirstClass(VRT.Generators.Tests.NonZeroFirst.Zero)
        });

        public static NonZeroFirstClass Empty { get; } = ValueByNameMap["Zero"];

        /// <summary>
/// Alpha
/// </summary>
        public const string Alpha = "Alpha";
        /// <summary>
/// Beta
/// </summary>
        public const string Beta = "Beta";
        /// <summary>
/// Zero
/// </summary>
        public const string Zero = "Zero";

        /// <summary>
/// Alpha
/// </summary>
        public static NonZeroFirstClass AlphaInstance { get; } = ValueByNameMap["Alpha"];
        /// <summary>
/// Beta
/// </summary>
        public static NonZeroFirstClass BetaInstance { get; } = ValueByNameMap["Beta"];
        /// <summary>
/// Zero
/// </summary>
        public static NonZeroFirstClass ZeroInstance { get; } = ValueByNameMap["Zero"];
    }
}