//HintName: FeatureFlagClass_Constructors.g.cs
// <auto-generated />
#nullable enable
namespace VRT.Generators.Tests
{
    public partial class FeatureFlagClass : global::System.IEquatable<FeatureFlagClass>
    {
        private FeatureFlagClass(VRT.Generators.Tests.FeatureFlags value)
        {
            Name = value.ToString();
            IsEmpty = value == default(VRT.Generators.Tests.FeatureFlags);
            Value = value;
            
        }
        public string Name { get; }
        public VRT.Generators.Tests.FeatureFlags Value { get; }
        public bool IsEmpty { get; }

        
        public bool HasAdminOnly { get; private init; }
        public bool Equals(FeatureFlagClass? other)
    => other is not null && other.Value == Value;

public override bool Equals(object? obj)
    => obj is FeatureFlagClass other && Equals(other);

public override int GetHashCode() => Value.GetHashCode();

public static bool operator ==(FeatureFlagClass? left, FeatureFlagClass? right)
    => left is null ? right is null : left.Equals(right);

public static bool operator !=(FeatureFlagClass? left, FeatureFlagClass? right)
    => !(left == right);

        public override string ToString() => Name;

        public static global::System.Collections.Generic.IReadOnlyCollection<FeatureFlagClass> GetAll() => ValueByNameMap.Values;

        public static global::System.Collections.Generic.IEnumerable<FeatureFlagClass> GetByName(global::System.Collections.Generic.IEnumerable<string> names)
            => global::System.Linq.Enumerable.Where(global::System.Linq.Enumerable.Select(names, GetByName), static p => p.IsEmpty == false);

        public static FeatureFlagClass GetByName(string name)
        {
            return ValueByNameMap.TryGetValue(name, out var value)
                ? value
                : Empty;
        }

        public static bool TryGetByName(string name, out FeatureFlagClass value)
        {
            if (ValueByNameMap.TryGetValue(name, out value!))
            {
                return true;
            }

            value = Empty;
            return false;
        }

        public static implicit operator FeatureFlagClass(string name) => GetByName(name);
        public static implicit operator string(FeatureFlagClass value) => value.Name;
        public static implicit operator VRT.Generators.Tests.FeatureFlags(FeatureFlagClass value) => value.Value;
        public static implicit operator FeatureFlagClass(VRT.Generators.Tests.FeatureFlags value) => GetByName(value.ToString());
        public static implicit operator int(FeatureFlagClass value) => (int) value.Value;
        public static implicit operator FeatureFlagClass(int value) => (VRT.Generators.Tests.FeatureFlags)value;
    }
}