//HintName: FeatureFlagClass_Constants.g.cs
// <auto-generated />
#nullable enable

namespace VRT.Generators.Tests
{
    public partial class FeatureFlagClass : global::System.IEquatable<FeatureFlagClass>
    {
        private static readonly global::System.Collections.ObjectModel.ReadOnlyDictionary<string, FeatureFlagClass> ValueByNameMap = new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, FeatureFlagClass>(new global::System.Collections.Generic.Dictionary<string, FeatureFlagClass>()
        {
            ["Sensitive"] = new FeatureFlagClass(VRT.Generators.Tests.FeatureFlags.Sensitive) { HasAdminOnly = true },
            ["Public"] = new FeatureFlagClass(VRT.Generators.Tests.FeatureFlags.Public) { HasAdminOnly = false }
        });

        public static FeatureFlagClass Empty { get; } = ValueByNameMap["Sensitive"];

        /// <summary>
        /// Sensitive
        /// </summary>
        public const string Sensitive = "Sensitive";
        /// <summary>
        /// Public
        /// </summary>
        public const string Public = "Public";

        /// <summary>
        /// Sensitive
        /// </summary>
        public static FeatureFlagClass SensitiveInstance { get; } = ValueByNameMap["Sensitive"];
        /// <summary>
        /// Public
        /// </summary>
        public static FeatureFlagClass PublicInstance { get; } = ValueByNameMap["Public"];
    }
}